### ISSUE TITLE
Thoughts after reading paper

### ISSUE THREAD

**Issue by NikitaMishin** [ctralie/jsGPUAlignment#5]
Not quite understand why we can't simply apply an anti-diagonal pattern to dp non-recrusive version of [DTW](https://en.wikipedia.org/wiki/Dynamic_time_warping#:~:text=In%20time%20series%20analysis%2C%20dynamic,which%20may%20vary%20in%20speed.&text=A%20well%20known%20application%20has,cope%20with%20different%20speaking%20speeds.). This will allow us to get linear space usage and easy parallelization on GPU? 
Have I missed something?

**Comment by ctralie** [comment]
Thanks for asking this. That will work fine for computing the optimal cost.
But unless you store all of the backpointers in memory, it's not possible
to figure out an optimal alignment path. So the divide and conquer
technique gets around this by extracting parts of an alignment path by
looking at cost only. Does that make sense?

**Comment by NikitaMishin** [comment]
Yep, now get it, thanks!)

**Comment by ctralie** [comment]
Glad I could clear it up!  I honestly started this project with your exact
thoughts, but then realized pretty quickly that I wouldn't be able to get
an alignment after throwing out all of the backpointers.
