### ISSUE TITLE
Window constraints

### ISSUE THREAD

**Issue by radkoff** [ctralie/jsGPUAlignment#7]
Hi, thanks for this library. Are there any plans to add local and global windowing constraints? I'm interested in asymmetric local windows that retain the original time series size, and global windows that don't stray too far from the main diagonal.

**Comment by ctralie** [comment]
Hello, thank you for your interest in the library!  Actually, I added support for a Sakoe-Chiba band in version 0.1.6 back in April.  I just updated the documentation, and you can see an example here:
http://www.ctralie.com/Research/linmdtw/notebooks/BasicUsage.html#Constrained-DTW-(CDTW)
As for asymmetric windows, I have no immediate plans, but I would welcome pull requests!
Hope that helps.
Best,
Chris

**Comment by ctralie** [comment]
Hi @radkoff, just curious what your thoughts are on this, and if we should leave this issue open

**Comment by radkoff** [comment]
Thanks for the info. It turns out the asymmetry is a dealbreaker for me. I'm still working out whether DTW is the right approach for what I'm working on, and if so, I may circle back with a pull request!
