### ISSUE TITLE
Minimum at the end of a diagonal causes crash

### ISSUE THREAD

**Issue by lvlanson** [ctralie/jsGPUAlignment#9]
Hi there,

during training of the classifier using your implementation I came across an edge case, which causes a crash.

`IndexError: index 1999 is out of bounds for axis 0 with size 1999`

I managed to narrow down, what the problem is, but I am not sure to fix it correctly. I provide you with the vectors I used to force this problem.

The error occurs inside the main function `linmdtw` in line 326. When you use these vectors you will have the following parameters:

```
box = [0, 1999, 0, 1999]
k_save = 2000
k = 0
idx = 1999
diagsum.shape = (2000,)
```

As you can see the index for the current diagonal is 1999. After we use the function `get_diag_indices` for creating the indices, we get these:

```
i = array([1998, 1997, 1996, ...,    2,    1,    0])
j = array([   0,    1,    2, ..., 1996, 1997, 1998])
```
So we are missing an index in that array.

I was trying to pass `diagsum.shape[0]-1` to the function and compared the results with the basic dtw algorithm, which showed my "fix" was wrong. I will try to continue fixing it, but maybe you're
[vectors.txt](https://github.com/ctralie/linmdtw/files/7169342/vectors.txt)
 faster than me.

**Comment by ctralie** [comment]
Darn! Thanks for the detailed info! I'll try to have a look as soon as I can

**Comment by lvlanson** [comment]
The error only occurs if you use 

```linmdtw(x,m, do_gpu=False)```

With GPU it works flawlessly

you can recreate the error currently easily with examples which exceed the `min_dim` parameter, everything below that works as expected:

```
import numpy as np
from linmdtw import linmdtw
length = 10 # 10 is crashing, 10 is not

x = length*[9]
y = length*[0]

x[0] = 0
y[length-1] = 9

x = np.array(x).reshape(-1,1)
y = np.array(y).reshape(-1,1)

linmdtw(x,y, min_dim=length, do_gpu=False)
```

**Comment by ctralie** [comment]
Thanks for the additional info!  Glad it works with the GPU for the time
being.  Will try to get this looked at ASAP

**Comment by lvlanson** [comment]
There is something really odd about the `dtw_diag` function.

Using the example from above, I use `x = [0,9,9,9]` and `y=[0,0,0,9]`.

So if I do this by hand I get the following results:
```
diag_left

     0    9    9    9  
  ─────────────────────
0 ┃    ┃    ┃ 18 ┃ 27 ┃
0 ┃    ┃  9 ┃ 18 ┃ 27 ┃
0 ┃  0 ┃  9 ┃ 18 ┃    ┃
9 ┃  9 ┃  0 ┃    ┃    ┃
  ─────────────────────

diag_right

     0     9     9    9  
  ─────────────────────
0 ┃    ┃    ┃ 27 ┃ 27 ┃
0 ┃    ┃ 18 ┃ 18 ┃ 18 ┃
0 ┃  0 ┃  9 ┃  9 ┃    ┃
9 ┃  9 ┃  0 ┃    ┃    ┃
  ─────────────────────

costmatrix

     0     9     9    9  
  ─────────────────────
0 ┃    ┃    ┃  9 ┃  9 ┃
0 ┃    ┃  9 ┃  9 ┃  9 ┃
0 ┃  0 ┃  9 ┃  9 ┃    ┃
9 ┃  9 ┃  0 ┃    ┃    ┃
  ─────────────────────

diag_right + diag_left - costmatrix

     0     9     9    9  
  ─────────────────────
0 ┃    ┃    ┃ 36 ┃ 45 ┃
0 ┃    ┃ 18 ┃ 27 ┃ 36 ┃
0 ┃  0 ┃  9 ┃ 18 ┃    ┃
9 ┃  9 ┃  0 ┃    ┃    ┃
  ─────────────────────
```

If I use `dtw_diag` I get the following outputs. I printed the outputs inside `dtw.py` after line 305

```
dleft=array([ 9.,  0.,  0., -1.], dtype=float32)
dright=array([-1., 18.,  9.,  0.], dtype=float32)
csmright=array([0., 9., 9., 0.], dtype=float32)
diagsum=[ 8. 27. 18. -1.]

dleft=array([18.,  9.,  0.,  0.], dtype=float32)
dright=array([18.,  9.,  0.,  0.], dtype=float32)
csmright=array([9., 9., 9., 9.], dtype=float32)
diagsum=[45. 27.  9.  9.]

dleft=array([18.,  9.,  0., -1.], dtype=float32)
dright=array([-1.,  9.,  0.,  0.], dtype=float32)
csmright=array([0., 9., 9., 0.], dtype=float32)
diagsum=[17. 27.  9. -1.]
```

As you can see the sums are quite a bit off from the diagonals next to the middle one. Also there shouldn't be a -1, which corrupts the results, as far as I can see.

I will keep you updated on what I find out about it.

**Comment by lvlanson** [comment]
There is something really odd about the `dtw_diag` function.

Using the example from above, I use `x = [0,9,9,9]` and `y=[0,0,0,9]`.

So if I do this by hand I get the following results:
```
diag_left

     0    9    9    9  
  ─────────────────────
0 ┃    ┃    ┃ 18 ┃ 27 ┃
0 ┃    ┃  9 ┃ 18 ┃ 27 ┃
0 ┃  0 ┃  9 ┃ 18 ┃    ┃
9 ┃  9 ┃  0 ┃    ┃    ┃
  ─────────────────────

diag_right

     0    9    9    9  
  ─────────────────────
0 ┃    ┃    ┃ 27 ┃ 27 ┃
0 ┃    ┃ 18 ┃ 18 ┃ 18 ┃
0 ┃  0 ┃  9 ┃  9 ┃    ┃
9 ┃  9 ┃  0 ┃    ┃    ┃
  ─────────────────────

costmatrix

     0    9    9    9  
  ─────────────────────
0 ┃    ┃    ┃  9 ┃  9 ┃
0 ┃    ┃  9 ┃  9 ┃  9 ┃
0 ┃  0 ┃  9 ┃  9 ┃    ┃
9 ┃  9 ┃  0 ┃    ┃    ┃
  ─────────────────────

diag_right + diag_left - costmatrix

     0    9    9    9  
  ─────────────────────
0 ┃    ┃    ┃ 36 ┃ 45 ┃
0 ┃    ┃ 18 ┃ 27 ┃ 36 ┃
0 ┃  0 ┃  9 ┃ 18 ┃    ┃
9 ┃  9 ┃  0 ┃    ┃    ┃
  ─────────────────────
```

If I use `dtw_diag` I get the following outputs. I printed the outputs inside `dtw.py` after line 305

```
dleft=array([ 9.,  0.,  0., -1.], dtype=float32)
dright=array([-1., 18.,  9.,  0.], dtype=float32)
csmright=array([0., 9., 9., 0.], dtype=float32)
diagsum=[ 8. 27. 18. -1.]

dleft=array([18.,  9.,  0.,  0.], dtype=float32)
dright=array([18.,  9.,  0.,  0.], dtype=float32)
csmright=array([9., 9., 9., 9.], dtype=float32)
diagsum=[45. 27.  9.  9.]

dleft=array([18.,  9.,  0., -1.], dtype=float32)
dright=array([-1.,  9.,  0.,  0.], dtype=float32)
csmright=array([0., 9., 9., 0.], dtype=float32)
diagsum=[17. 27.  9. -1.]
```

As you can see the sums are quite a bit off from the diagonals next to the middle one. Also there shouldn't be a -1, which corrupts the results, as far as I can see.

The `-1` also causes in `np.argmin(diagsum)` to return indices, which cause the indexerror.

I will keep you updated on what I find out about it.

**Comment by lvlanson** [comment]
Something seems to be wrong with the `diag_step.cpp`. I was tracking the outputs for the diagonals and costmatrix-diagonals. While the costmatrix-diagonals are correct, the diagonals for the accumulated costmatrix seem to be wrong.

This output was generated inside the `dtw_diag` function. I outputted all cost and diagonal data in `line 209`. In the next graphic I will show you how the accumulated cost-matrix should look like, if we are exclusively looking at d2. The graphic shows, what the matrix should look like, 'Output' shows what `dtw_diag` does and 'Expected' shows what normally should be seen. This will be only shown for the forward direction. The problem is for the reverse direction exactly the same.
```
d2
k=0
     0    9    9    9  
  ─────────────────────
0 ┃  0 ┃    ┃    ┃    ┃
0 ┃    ┃    ┃    ┃    ┃
0 ┃    ┃    ┃    ┃    ┃
9 ┃    ┃    ┃    ┃    ┃
  ─────────────────────
Output:
d2=array([ 0., -1., -1., -1.], dtype=float32)

Expected:
d2=array([ 0., -1., -1., -1.], dtype=float32)

===============================================

d2
k=1
     0    9    9    9  
  ─────────────────────
0 ┃    ┃  9 ┃    ┃    ┃
0 ┃  0 ┃    ┃    ┃    ┃
0 ┃    ┃    ┃    ┃    ┃
9 ┃    ┃    ┃    ┃    ┃
  ─────────────────────
Output:
d2=array([ 0.,  0., -1., -1.], dtype=float32)
           ^
Expected:
d2=array([ 9.,  0., -1., -1.], dtype=float32)
           ^
===============================================

d2
k=2
     0    9    9    9  
  ─────────────────────
0 ┃    ┃    ┃ 18 ┃    ┃
0 ┃    ┃  9 ┃    ┃    ┃
0 ┃  0 ┃    ┃    ┃    ┃
9 ┃    ┃    ┃    ┃    ┃
  ─────────────────────
Output:
d2=array([ 9.,  0.,  0., -1.], dtype=float32)
           ^    ^
Expected:
d2=array([ 18.,  9.,  0., -1.], dtype=float32)
           ^     ^

===============================================

d2
k=3
     0    9    9    9  
  ─────────────────────
0 ┃    ┃    ┃    ┃ 27 ┃
0 ┃    ┃    ┃ 18 ┃    ┃
0 ┃    ┃  9 ┃    ┃    ┃
9 ┃  9 ┃    ┃    ┃    ┃
  ─────────────────────

Output:
d2=array([18.,  9.,  0.,  0.], dtype=float32)
           ^    ^    ^    ^
Expected:
d2=array([27.,  18.,  9.,  9.], dtype=float32)
           ^     ^    ^    ^

===============================================

d2
k=4
     0    9    9    9  
  ─────────────────────
0 ┃    ┃    ┃    ┃    ┃
0 ┃    ┃    ┃    ┃ 27 ┃
0 ┃    ┃    ┃ 18 ┃    ┃
9 ┃    ┃  0 ┃    ┃    ┃
  ─────────────────────

Output:
d2=array([18.,  9.,  0., -1.], dtype=float32)
           ^    ^
Expected:
d2=array([27.,  18.,  0., -1.], dtype=float32)
           ^     ^
k == k_end => break
```

**Comment by lvlanson** [comment]
I just found out, that the gpu version is also faulty. I have been able to fix the CPU version by now. I will try to fix the gpu version too

```
import numpy as np
from linmdtw import linmdtw
from fastdtw import fastdtw, dtw
length = 4

x = length*[9]
y = length*[0]

#x = np.random.randint(length, size=length)
#y = np.random.randint(length, size=length)

x[0] = 0
y[length-1] = 9

x = np.array(x).reshape(-1,1)
y = np.array(y).reshape(-1,1)

print(linmdtw(x,y, min_dim=4, do_gpu=False))
print(linmdtw(x,y, min_dim=4, do_gpu=True))
print(dtw(x,y))
```

The output after my fix for the cpu version looks like this

```
# linmdtw GPU = False
[[0 0]
 [0 1]
 [0 2]
 [1 3]
 [2 3]
 [3 3]]

# linmdtw GPU = True
[[0 0]
 [0 1]
 [1 2]
 [2 3]
 [3 3]]

# Vanilla DTW
(0.0, [(0, 0), (0, 1), (0, 2), (1, 3), (2, 3), (3, 3)])
```

**Comment by ctralie** [comment]
This is great, thank you so much for your help!  I'm in the middle of a
semester teaching and my dev time is limited, so I really appreciate how
much you're digging into it.  What we should do is create unit tests that
fail before the fixes you make but pass afterwards.  Then, you can make a
pull request and I'll update the official release

**Comment by lvlanson** [comment]
Will do so, I am about to finish my thesis. I want to run my experiments, so I try to fix it. Its still not stable somehow, but I am about to understand your code now. I will go ahead and continue fixing the issue.

For the test case I could run some random samples with low dimensionality against vanilla dtw and see if there still are issues.

**Comment by ctralie** [comment]
I will see if I can find some time tomorrow to help if needed.
The unit tests can be exactly what you've been testing it with here to
start with.

**Comment by lvlanson** [comment]
I will try to solve it today, I can explain you where I think the problem was. I think very important edge cases are, when the path goes at the very border of the matrix, that where the crashes happened.

I will keep you updated, hopefully soon with a merge request.

**Comment by ctralie** [comment]
Thank you again!   You are a hero with the debugging here!

**Comment by lvlanson** [comment]
I created a pull request. We can meet within the next weeks in an online meeting, if you'd like to discuss to further improve something. Hopefully this fixes the issues. I tried some examples and checked if the paths are valid. Naturally the paths might differ from vanilla dtw, if there are different paths of same cost. So I checked from my experiments all the unequal paths if the solution still is valid. So far it seems to work.

Edit:

I did not incorporate a test environment yet. I'd suggest to speak on how to proceed on this a little later.

**Comment by ctralie** [comment]
Hello, I was unable to finish going through this today.  What you wrote
seems to work, but I need more time before I can confidently push to an
official release.  In the meantime, are you able to setup an environment
where you can run your code locally, so you can proceed?  Thank you again
for your interest and investment in this library!

**Comment by lvlanson** [comment]
Glad to hear, that my fixes seem to work so far.

Take your time, there is no rush from my end. Today I will try to get my setup going again. I will try your instructions from the other issue.

I can offer to you, that we can go through the changes via audio/video conference with screen sharing and we can talk about this in depth. Maybe this can speed up our understanding about whats happening. You probably still have my mail address, since I wrote you not too long ago. It should start with "tdavies".

Also we could talk about some future changes for testing and 64-bit support, where I could try to help out too.

**Comment by lvlanson** [comment]
Hey there,

is there any update on how to proceed with the library to fix the issue?

Kind Regards

**Comment by ctralie** [comment]
Hey good news @lvlanson, I finally fixed this!  You've probably moved on by now, but in case you haven't, I'll fix this up and commit this tomorrow.  The error was incredibly subtle and took me a couple of hours to find.  Also, I decided to keep the original design of not adding on the csm to the diagonal elements, even though this conflicts slightly with what I wrote in the paper.  More updates soon...

**Comment by lvlanson** [comment]
Glad that I could help identifying this problem. Yes, my solution was sticking to the procedure of the paper. I also incorporated my solution on this algorithm in my bachelor's thesis. Unfortunately it is written in German and probably not much of use for you. But if you are interested, you can see it here.

https://www.researchgate.net/publication/357975656_Implementation_und_Komplexitatsanalyse_von_Learning_Vector_Quantization_in_Dynamic_Time_Warping_Raumen

**Comment by ctralie** [comment]
Great!  I'm glad you were able to keep moving even while I was completely
occupied with teaching activities.  The problem turned out to be related to
incorrect sizing of the diagonal elements in some corner cases.
